# Generated by Django 2.1.3 on 2018-11-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='connections',
        ),
        migrations.AddField(
            model_name='member',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=False),
        ),
    ]
