# Generated by Django 2.1.3 on 2018-11-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchingapp', '0002_auto_20181112_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='desc',
        ),
    ]
