# Generated by Django 2.1.3 on 2018-11-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingapp', '0004_auto_20181124_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='match_requests',
            field=models.ManyToManyField(blank=True, to='matchingapp.Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='_member_matches_+', to='matchingapp.Member'),
        ),
    ]
