# Generated by Django 2.1.3 on 2018-11-25 17:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchingapp', '0005_auto_20181124_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(default=datetime.datetime.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchingapp.Conversation')),
                ('read_by', models.ManyToManyField(blank=True, null=True, related_name='ready_by', to='matchingapp.Member')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matchingapp.Member')),
            ],
        ),
    ]
