# Generated by Django 2.1.3 on 2018-11-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingapp', '0006_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='name',
        ),
        migrations.AddField(
            model_name='conversation',
            name='foo',
            field=models.CharField(default='foo', max_length=10),
        ),
    ]
