# Generated by Django 2.1.3 on 2018-11-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingapp', '0007_auto_20181125_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='foo',
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(blank=True, to='matchingapp.Member'),
        ),
    ]
