# Generated by Django 2.1.3 on 2018-11-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingapp', '0008_auto_20181125_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(default='foo', max_length=100),
            preserve_default=False,
        ),
    ]
