# Generated by Django 2.1.3 on 2018-12-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingapp', '0010_message_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read_by',
            field=models.ManyToManyField(related_name='ready_by', to='matchingapp.Member'),
        ),
    ]
